### ISSUE TITLE
getUrlParameter proposal

### ISSUE THREAD

**Issue by cawa-93** [PlayShikiApp/PlayShikiApp#4]
https://github.com/PlayShikiApp/PlayShikiApp/blob/e13560e4f338fd03a26a0d310e31b000dad93807/src/players/anilibria/js/anilibria.js#L1-L12

https://github.com/PlayShikiApp/PlayShikiApp/blob/e13560e4f338fd03a26a0d310e31b000dad93807/app/static/js/parse_url.js#L1-L14

https://github.com/PlayShikiApp/PlayShikiApp/blob/e13560e4f338fd03a26a0d310e31b000dad93807/src/static/js/render.js#L115-L131

```js
function getUrlParameter (href, param) {
  if (!href || !param) {
    console.error(`Can't find ${param} in ${href}`, {error: 'href or param is empty'})
    return null
  }

  try {
    return new URL(href).searchParams.get(param)
  } catch (error) { // href is not valid URL
    console.error(`Can't find ${param} in ${href}`, {error})
    return null
  }
}
```

**Comment by ChronoMonochrome** [comment]
В render.js забрал, переписанный вариант, спасибо.
В anilibria.js неправильный формат URL, поэтому пример кода выше не работает, пока оставлю как есть.
